import { Inter } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<ol>
					<li>
						<Link href={"/"}>Home</Link>
					</li>
					<li>
						<a href="/">Home</a>
					</li>
					<li>
						<Link href={"/about"}>About</Link>
					</li>
					<li>
						<a href="/about">About</a>
					</li>
					<li>
						<a href="/about/user">User</a>
					</li>
				</ol>
			</header>
			<h1>This is HomePage</h1>
		</>
	);
}
